#!/usr/bin/python
# -*- coding: utf-8 -*-

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")

# Script arguments
MasterCompanyPortfolios_Update = arcpy.GetParameterAsText(0)
if MasterCompanyPortfolios_Update == '#' or not MasterCompanyPortfolios_Update:
    MasterCompanyPortfolios_Update = "D:\\PLS\\AutoWorkflow\\FinalOutputs.gdb\\MasterCompanyPortfolios_Update" # provide a default value if unspecified

# Local variables:
I_MasterCompanyPortfolios_Update_FILENAME = MasterCompanyPortfolios_Update
Value = "1"
CompanyPortfolios_gdb = "D:\\PLS\\AutoWorkflow\\CompanyPortfolios.gdb"
v_Value_ = "D:\\PLS\\AutoWorkflow\\CompanyPortfolios.gdb\\%Value%"

# Process: Iterate Feature Selection
arcpy.IterateFeatureSelection_mb(MasterCompanyPortfolios_Update, "FILENAME #", "false")

# Process: Feature Class to Feature Class
arcpy.FeatureClassToFeatureClass_conversion(I_MasterCompanyPortfolios_Update_FILENAME, CompanyPortfolios_gdb, "%Value%", "", "COMPANY \"COMPANY\" true true false 255 Text 0 0 ,First,#,I_MasterCompanyPortfolios_Update_FILENAME,COMPANY,-1,-1;CompanyID \"CompanyID\" true true false 8 Text 0 0 ,First,#,I_MasterCompanyPortfolios_Update_FILENAME,CompanyID,-1,-1;DATE \"DATE\" true true false 8 Date 0 0 ,First,#,I_MasterCompanyPortfolios_Update_FILENAME,DATE,-1,-1;FILENAME \"FILENAME\" true true false 100 Text 0 0 ,First,#,I_MasterCompanyPortfolios_Update_FILENAME,FILENAME,-1,-1;UPDATED \"UPDATED\" true true false 8 Date 0 0 ,First,#,I_MasterCompanyPortfolios_Update_FILENAME,UPDATED,-1,-1;Shape_Length \"Shape_Length\" false true true 8 Double 0 0 ,First,#,I_MasterCompanyPortfolios_Update_FILENAME,Shape_Length,-1,-1;Shape_Area \"Shape_Area\" false true true 8 Double 0 0 ,First,#,I_MasterCompanyPortfolios_Update_FILENAME,Shape_Area,-1,-1", "")

